### ISSUE TITLE
Add MAC address filter for clients coming from XLink Kai

### ISSUE THREAD

**Issue by codedwrench** [codedwrench/mondevtopromisc#6]
When sending packets it seems to sometimes pick up its own sent packets causing some unnecessary extra traffic. This program should recognize MAC addresses coming from XLink Kai and block those addresses from being received again on the monitor mode device.

**Comment by CrunchBite** [comment]
When implementing this special care needs to be taken for multicast (01-00-5E and 33-33-00 through 33-33-FF), LLDP (01-80-C2), and of course broadcasts.
